version: "3.3"
services:
  # Service registration
  consul:
    command: agent -dev -client 0.0.0.0
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  # Elasticsearh as DATABASE
  elasticsearch:
    image: elasticsearch:1.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_HEAP_SIZE: 512m
      ES_CLUSTER_NAME: Kazoup

  # zookeeper and kafka as message broker
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1

  # go-micro tools
  api:
    command: --registry_address=consul:8500 --enable_stats --register_interval=5 --register_ttl=10 api --handler=http
    image: microhq/micro:latest
    depends_on:
      - consul
    ports:
      - "8080:8080"
  web:
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 web
    image: microhq/micro:latest
    depends_on:
      - consul
    ports:
      - "8082:8082"
   
  
  # sidecar:
  #   command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 sidecar
  #   image: microhq/micro:latest
  #   depends_on:
  #     - consul
  #   ports:
  #     - "8081:8081"
  
  # ML Mutant microservices
  # mutant:
  #   image: rodrigodmd/ml-mutant-srv:mutant
  #   build: ./srv/mutant
  #   command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 --broker_address=kafka1:9092 --start_wait_time=20
  #   links:
  #     - consul
  #     - kafka1

  # stats:
  #   image: rodrigodmd/ml-mutant-srv:stats
  #   build: ./srv/stats
  #   command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 --elasticsearch_hosts=elasticsearch:9200 --broker_address=kafka1:9092 --start_wait_time=20
  #   links:
  #     - consul
  #     - elasticsearch
  #     - kafka1

  gateway:
    image: rodrigodmd/ml-mutant-srv:gateway
    build: ./srv/gateway
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10
    links:
      - consul
