apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: elasticsearch:1.7.1
    generation: null
    importPolicy: {}
    name: 1.7.1
status:
  dockerImageRepository: ""
