apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    io.kompose.service: elasticsearch
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_CLUSTER_NAME
          value: Kazoup
        - name: ES_HEAP_SIZE
          value: 512m
        image: ' '
        name: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - elasticsearch
      from:
        kind: ImageStreamTag
        name: elasticsearch:1.7.1
    type: ImageChange
status: {}
