apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: rodrigodmd/ml-mutant-srv:gateway
    generation: null
    importPolicy: {}
    name: gateway
status:
  dockerImageRepository: ""
