apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    io.kompose.service: gateway
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - args:
        - --registry_address=consul:8500
        - --register_interval=5
        - --register_ttl=10
        image: ' '
        name: gateway
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gateway
      from:
        kind: ImageStreamTag
        name: gateway:gateway
    type: ImageChange
status: {}
