apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mutant
  name: mutant
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: rodrigodmd/ml-mutant-srv:mutant
    generation: null
    importPolicy: {}
    name: mutant
status:
  dockerImageRepository: ""
