apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mutant
  name: mutant
spec:
  replicas: 1
  selector:
    io.kompose.service: mutant
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mutant
    spec:
      containers:
      - args:
        - --registry_address=consul:8500
        - --register_interval=5
        - --register_ttl=10
        image: ' '
        name: mutant
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mutant
      from:
        kind: ImageStreamTag
        name: mutant:mutant
    type: ImageChange
status: {}
