apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: stats
  name: stats
spec:
  replicas: 1
  selector:
    io.kompose.service: stats
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stats
    spec:
      containers:
      - args:
        - --registry_address=consul:8500
        - --register_interval=5
        - --register_ttl=10
        - --elasticsearch_hosts=elasticsearch:9200
        image: ' '
        name: stats
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - stats
      from:
        kind: ImageStreamTag
        name: stats:stats
    type: ImageChange
status: {}
