apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: stats
  name: stats
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: rodrigodmd/ml-mutant-srv:stats
    generation: null
    importPolicy: {}
    name: stats
status:
  dockerImageRepository: ""
