version: "3"
services:
  # Neded services
  consul:
    command: agent -dev -client 0.0.0.0
    image: consul:latest
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

  api:
    command: --registry_address=consul:8500 --enable_stats --register_interval=5 --register_ttl=10 api --handler=http
    image: microhq/micro:latest
    depends_on:
      - consul
    ports:
      - "80:8080"
    labels:
      kompose.service.type: LoadBalancer

  web:
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 web
    image: microhq/micro:latest
    depends_on:
      - consul
    ports:
    - "8082:8082"

  elasticsearch:
    image: elasticsearch:1.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_HEAP_SIZE: 512m
      ES_CLUSTER_NAME: Kazoup

  # DNA Mutant microservices
  mutant:
    image: rodrigodmd/ml-mutant-srv:mutant
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10
    links:
      - consul

  stats:
    image: rodrigodmd/ml-mutant-srv:stats
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 --elasticsearch_hosts=elasticsearch:9200
    links:
      - consul
      - elasticsearch

  gateway:
    image: rodrigodmd/ml-mutant-srv:gateway
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10
    links:
      - consul
