apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mutant
  name: mutant
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mutant
    spec:
      containers:
      - args:
        - --registry_address=consul:8500
        - --register_interval=5
        - --register_ttl=10
        image: rodrigodmd/ml-mutant-srv:mutant
        name: mutant
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always
status: {}
